architecture: "replicaset"
replicaCount: 2

nodeSelector:
  app: xcmongo

resources:
  requests:
    cpu: 1000m
    memory: 2Gi
  limits:
    cpu: 4000m
    memory: 8Gi

auth:
  enabled: true

persistence:
  enabled: true
  size: 30Gi

customLivenessProbe:
  failureThreshold: 6
  initialDelaySeconds: 30
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 10
  exec:
    command:
      - /custom-scripts/mongoping

initContainers:
  - name: download-ping-tool
    image: busybox:1.36.0
    imagePullPolicy: Always
    command:
      - sh
      - -c
      - |
        #!/usr/bin/env bash -e
        wget -O /custom-scripts/mongoping.tar.gz \
        "https://github.com/nkprince007/mongoping/releases/download/1.0.0/mongoping_1.0.0_linux_amd64.tar.gz"
        cd /custom-scripts/ && tar -xzvf mongoping.tar.gz
        chmod +x /custom-scripts/mongoping
    volumeMounts:
      - mountPath: "/custom-scripts"
        name: mongodb-ping-volume

extraVolumeMounts:
  - name: mongodb-ping-volume
    mountPath: /custom-scripts

extraVolumes:
  - name: mongodb-ping-volume
    emptyDir:
      sizeLimit: 100Mi
